name: Hello

on:
  push:
    branches:
      -  main


jobs:
  my_first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checking the repository
        uses: actions/checkout@v4

      - name: Install nodejs
        run: sudo apt install nodejs

      - name: Start script
        run: node hello.js
